image: macos-monterey  # образ для сборки
stack: node 14  # окружение
branches:
  only:
    - master  # ветка git
cache: node_modules  # кеширование
install:
  - npm install  # команда установки зависимостей
build: off
test_script:
  - npm run lint  # скрипт сборки